  # description:
  
  in this test, the headers are stored within the expectation files.
  
  # response:
  
?                                                              | EOF
! test raised exception Expecting value: line 1 column 1 (char 0): | EOF
  Traceback (most recent call last):
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/requests/models.py", line 974, in json
      return complexjson.loads(self.text, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.pyenv/versions/3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/arau/lumoa/src/booktest/booktest/testrun.py", line 105, in run_case
      rv = await maybe_async_call(case, [t], {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 6, in maybe_async_call
      return await func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/requests.py", line 489, in wrapper
      return await maybe_async_call(func , args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 8, in maybe_async_call
      return func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/test/examples/snapshots_book.py", line 151, in test_saved_request
      t.tln(json.dumps(response.json()["json"], indent=4))
                       ^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/requests/models.py", line 978, in json
      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
