  # description:
  
  sometimes apis are stateful and we want to keep track of response sequence
  following requests should provide different answer
  
  # first response:
  
  
! test raised exception _ssl.c:989: The handshake operation timed out: | EOF
  Traceback (most recent call last):
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
      yield
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
      resp = self._pool.handle_request(req)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
      raise exc from None
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
      response = connection.handle_request(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
      raise exc
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
      stream = self._connect(request)
               ^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 156, in _connect
      stream = stream.start_tls(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 154, in start_tls
      with map_exceptions(exc_map):
    File "/home/arau/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
      self.gen.throw(typ, value, traceback)
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
      raise to_exc(exc) from exc
  httpcore.ConnectTimeout: _ssl.c:989: The handshake operation timed out
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/arau/lumoa/src/booktest/booktest/testrun.py", line 105, in run_case
      rv = await maybe_async_call(case, [t], {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 6, in maybe_async_call
      return await func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/httpx.py", line 421, in wrapper
      return await maybe_async_call(func , args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 8, in maybe_async_call
      return func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/test/examples/snapshots_book.py", line 71, in test_httpx_sequence
      response = httpx.get("https://timeapi.io/api/time/current/zone?timeZone=Europe%2FAmsterdam")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_api.py", line 210, in get
      return request(
             ^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_api.py", line 118, in request
      return client.request(
             ^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 837, in request
      return self.send(request, auth=auth, follow_redirects=follow_redirects)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
      response = self._send_handling_auth(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
      response = self._send_handling_redirects(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
      response = self._send_single_request(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
      response = transport.handle_request(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/httpx.py", line 299, in mocked_handle_request
      return self.handle_request(transport, request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/httpx.py", line 273, in handle_request
      return self.snapshot_request(transport, request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/httpx.py", line 266, in snapshot_request
      rv = self._real_handle_request(transport, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
      with map_httpcore_exceptions():
    File "/home/arau/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
      self.gen.throw(typ, value, traceback)
    File "/home/arau/.cache/pypoetry/virtualenvs/booktest-OySOPCsb-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
      raise mapped_exc(message) from exc
  httpx.ConnectTimeout: _ssl.c:989: The handshake operation timed out
  
